project_id = "vjpaolkqlumpyuxxmmvr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://hiremebuddy.na"
additional_redirect_urls = ["https://lovableproject.com", "http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.reset-password]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.reverse-geocode]
verify_jwt = false